---

- name: reboot instance
  hosts: all
  gather_facts: no
  tasks: 
    - name: Restart server
      command: /sbin/shutdown -r +1
      async: 0
      poll: 0
      ignore_errors: true
      become: yes
