---

- name: yum repos are installed
  yum:
    name: "{{ item }}"
    state: present
  become: yes
  with_items:
      - epel-release
      - https://mirror.webtatic.com/yum/el7/webtatic-release.rpm

- name: configure packages
  yum:
    name: "{{ item }}"
    state: present
    update_cache: yes
  become: yes
  with_items: "{{ packages }}"

- name: configure iptables
  template:
    src: iptables
    dest: /etc/sysconfig/iptables
  become: yes
  notify:
      - reload iptables

- name: configure 
  template:
    src: "{{ item }}"
    dest: "/{{ item }}"
  become: yes
  notify:
      - reload php-fpm
      - reload nginx
  with_items:
    - etc/php.ini
    - etc/php-fpm.d/www.conf
    - etc/nginx/conf.d/default.conf
    - etc/nginx/nginx.conf
    - etc/cron.d/50-certbot

- name: selinux is disabled
  selinux:
    state: disabled
  become: yes

- name: configure services
  systemd:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    enabled: "{{ item.enabled }}"
    daemon_reload: yes
  become: yes
  ignore_errors: yes
  with_items: "{{ services }}"
